### ISSUE TITLE
Higher input resolution?

### ISSUE THREAD

**Issue by puppet101** [elliottwu/unsup3d#5]
Hi, the input face size is 64*64 which is too small, have you tried higher resolution for better image quality?

**Comment by elliottwu** [comment]
Hi! 
We did try 128x128 at some point, but I do not have a completed model at the moment. It should be quite straightforward to add one more downsampling/upsampling layer to the encoder/decoder networks. But training will be ~4 times slower because of the rendering. And you might also need to adjust the perceptual loss, eg, using a deeper layer.
