### ISSUE TITLE
Output form of the model

### ISSUE THREAD

**Issue by VoiceBeer** [elliottwu/unsup3d#6]
Hi, thx for your work, very impressive!

I got a query about the output form of the mode. To my knowledge, the output (reconstruction) and the canonical view are all 2D images, but with depth value which could be used to reconstruct 3D volumes. Is that right? Or canonical view (reconstruction image) is a 3D volume already?

Again thank you for your work and code, looking forward to your reply :>.

**Comment by elliottwu** [comment]
Hi! 
The output of our model is depth maps in canonical viewpoint, as well as albedo, lighting, viewpoints and confidence maps. The way we render the results from various viewpoints is by constructing meshes from the depth maps, rather than 3D volumes. Maybe this demo code can be helpful: https://github.com/elliottwu/unsup3d/blob/30f4550b6bab6a520e9dd005dadac637b2fb9eb6/demo/demo.py#L196.

**Comment by VoiceBeer** [comment]
Hi, Many thx!

Have a good day :)
