### ISSUE TITLE
How to customize a higher resolution model?

### ISSUE THREAD

**Issue by stone100010** [elliottwu/unsup3d#9]
How to customize a higher resolution model?

**Comment by elliottwu** [comment]
Hi!

You could try to increase the output resolution of the networks by adding more upsampling layers. A couple of potential issues might arise when you try to increase the resolution to, say, 256x256: 
1. Higher resolution depth maps may result in crazy occlusion and the gradients through the renderer will be too noisy to learn anything meaningful, especially when the depth maps are noisy initially from randomly initialized network weights. But it is possible to add a smoothness loss on the depth maps. 
2. Training will much slower, mainly due to the rendering cost. 
3. The simple Lambertian model may not be powerful enough to render photorealistic images, even if it has a higher resolution. 

All of these are good research problems that can be tackled in future work.
